import os
import json

_LANG = "en"

_STRINGS = {
    "en": {
        "app_name": "FILE CONVERTER",
        "app_title": "FILE CONVERTER",
        "home": "Home",
        "conversion": "CONVERSION",
        "images": "Images",
        "documents": "Documents",
        "video": "Video",
        "audio": "Audio",
        "archives": "Archives",
        "data": "Data (CSV/JSON)",
        "history": "History",
        "history_title": "CONVERSION HISTORY",
        "history_empty": "history is empty",
        "settings": "Settings",
        "settings_title": "SETTINGS",
        "save_history": "Save history",
        "image_quality": "Image quality (JPEG / WEBP)",
        "audio_bitrate": "Audio bitrate (MP3)",
        "language": "Language",
        "file": "file",
        "browse": "BROWSE",
        "save_as": "save as:",
        "quality": "quality:",
        "bitrate": "bitrate:",
        "format": "format:",
        "convert": "CONVERT",
        "converting": "CONVERTING",
        "run": "RUN",
        "working": "PROCESSING",
        "done": "done",
        "error": "error",
        "select_file": "Select a file",
        "enter_name": "Enter output filename",
        "drop_file": "Drop a file here\nor click to select",
        "quick_actions": "quick actions",
        "recent": "recent conversions",
        "open": "open",
        "ready": "ready",
        "add": "ADD",
        "create": "CREATE",
        "extract": "EXTRACT",
        "files_to_archive": "files to archive",
        "select_archive": "select archive",
        "archive_created": "archive created",
        "extracted_to": "extracted to",
        "search_tool": "search tool...",
        "no_file": "no file selected",
        "convert_anything": "Convert any file — 58 formats, 6 categories",
        "click_to_select": "click to select",
        "image_formats": "29 formats — convert between any",
        "document_formats": "TXT ↔ PDF ↔ DOCX",
        "video_formats": "17 formats — convert between any",
        "audio_formats": "12 formats — convert between any",
        "archive_formats": "Create or extract ZIP / TAR / TAR.GZ",
        "data_formats": "CSV ⟷ JSON",
    },
    "ru": {
        "app_name": "FILE CONVERTOR",
        "app_title": "FILE CONVERTOR",
        "home": "Главная",
        "conversion": "КОНВЕРТАЦИЯ",
        "images": "Изображения",
        "documents": "Документы",
        "video": "Видео",
        "audio": "Аудио",
        "archives": "Архивы",
        "data": "Данные (CSV/JSON)",
        "history": "История",
        "history_title": "ИСТОРИЯ КОНВЕРТАЦИЙ",
        "history_empty": "история пуста",
        "settings": "Настройки",
        "settings_title": "НАСТРОЙКИ",
        "save_history": "Сохранять историю",
        "image_quality": "Качество изображений (JPEG / WEBP)",
        "audio_bitrate": "Битрейт аудио (MP3)",
        "language": "Язык",
        "file": "файл",
        "browse": "ВЫБРАТЬ",
        "save_as": "сохранить как:",
        "quality": "качество:",
        "bitrate": "битрейт:",
        "format": "формат:",
        "convert": "CONVERT",
        "converting": "КОНВЕРТАЦИЯ",
        "run": "RUN",
        "working": "ОБРАБОТКА",
        "done": "готово",
        "error": "ошибка",
        "select_file": "Выберите файл",
        "enter_name": "Укажите имя выходного файла",
        "drop_file": "Перетащите файл сюда\nили нажмите для выбора",
        "quick_actions": "быстрые действия",
        "recent": "недавние конвертации",
        "open": "открыть",
        "ready": "готов",
        "add": "ДОБАВИТЬ",
        "create": "СОЗДАТЬ",
        "extract": "РАСПАКОВАТЬ",
        "files_to_archive": "файлы для архивации",
        "select_archive": "выберите архив",
        "archive_created": "архив создан",
        "extracted_to": "распаковано в",
        "search_tool": "поиск инструмента...",
        "no_file": "файл не выбран",
        "convert_anything": "Конвертируйте любые файлы — 58 форматов, 6 категорий",
        "click_to_select": "нажмите для выбора",
        "image_formats": "29 форматов — конвертируйте между любыми",
        "document_formats": "TXT ↔ PDF ↔ DOCX",
        "video_formats": "17 форматов — конвертируйте между любыми",
        "audio_formats": "12 форматов — конвертируйте между любыми",
        "archive_formats": "Создать или распаковать ZIP / TAR / TAR.GZ",
        "data_formats": "CSV ⟷ JSON",
    },
}


def _(key):
    return _STRINGS.get(_LANG, _STRINGS["en"]).get(key, key)


def set_lang(lang):
    global _LANG
    if lang in _STRINGS:
        _LANG = lang


def get_lang():
    return _LANG
